# Site settings
title: Apps developed by Agiliq
email: "hello@agiliq.com"
description: "Agiliq builds amazing apps. Here are some open source apps we have developed."
baseurl: ""
url: "http://apps.agiliq.com"

# Build settings
markdown: kramdown
permalink: pretty
